i hate git branch
AlisaChu/front-end-pro pull request #12
Opened 2023-07-15 12:52 UTC by AlisaChu

я сделала домашку еще вчера, но по каким то мне невиданным причинам мой непревзойденный гит перестал показывать на какой я ветке нахожусь команда git branch никак больше его не беспокоит, он не показывает как раньше звезочку напротив ветки, поэтому я 12 часов училась чувствовать ветки что б сделать пул реквест!)

2023-07-15 14:01 UTC, volodymyr-kryvoshapov requested changes

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +addStudentBtn.addEventListener('click', function () {
этого не было в задаче, убрать

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +function renderStudent(student) {
этого не было в задаче, убрать

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +}
Откуда это все и зачем?!

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/student.js
> +    }
тут не хватает функции getMarksSum()

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +const addStudentBtn = document.getElementById('add-student-btn');
убрать все лишнее, делаем только то что в задании

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/group.js
> +    students = [];
Не выполнено условие: Массив students сделать readonly

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +function renderGroupAverage() {
этого не было в задаче, убрать

2023-07-15 14:01 UTC, volodymyr-kryvoshapov commented on student_oop/index_01.js
> +function clearInputs() {
этого не было в задаче, убрать

2023-07-15 14:25 UTC, AlisaChu commented on student_oop/index_01.js
> +}
это делается для того что бы можно было вводить с браузера имя студента и оценку и он считал

2023-07-18 19:07 UTC, volodymyr-kryvoshapov approved these changes

2023-07-18 19:07 UTC, volodymyr-kryvoshapov commented on student_oop/group.js
> +        return [...this.#students];
можно просто return this.#students

2023-07-19 14:50 UTC, merged